name: Windows EXE Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build exe
      run: |
        go install fyne.io/fyne/v2/cmd/fyne@latest
        go build -o swimtool.exe .

    - name: Upload .exe
      uses: actions/upload-artifact@v4
      with:
        name: SwimToolEXE
        path: swimtool.exe
        
